### ISSUE TITLE
Example Shading and SSAO

### ISSUE THREAD

**Issue by catfoolyou** [catfoolyou/Overhaul-Shader#3]
![image](https://user-images.githubusercontent.com/95507639/187231515-2efe2bb7-bb97-4974-9741-383b7a7231c0.png)
![image](https://user-images.githubusercontent.com/95507639/187231544-e48a81a5-233a-43af-977a-db85eef1456f.png)
![image](https://user-images.githubusercontent.com/95507639/187231570-2756247c-db1e-4c25-970c-c7a91cbf53c4.png)

**Comment by nskmda** [comment]
Are you studying at school or playing MC?!

**Comment by catfoolyou** [comment]
No lol

**Comment by catfoolyou** [comment]
https://lettier.github.io/3d-game-shaders-for-beginners/ssao.html
this might help
